### Test index route
GET http://127.0.0.1:8090/

### Test query route
GET http://127.0.0.1:8090/api/query_user/50/Alice

### Test error route
GET http://127.0.0.1:8090/api/query_user_error/30/Bob

### Test create route
POST http://127.0.0.1:8090/api/create_user
Content-Type: application/json

{
    "name": "Bob",
    "password": "a12345"
}
